package com.example.appcardapio.login.presentation

enum class LoginAction {
    NAVIGATE_HOME,
    SHOW_ACCOUNT_CREATED_MSG,
    SHOW_RECOVER_MSG,
    SHOW_ERROR_MSG,
    SHOW_ERROR_MSG_EMPTY,
    SHOW_ERROR_MSG_BAD_EMAIL_FORMAT,
    SHOW_ERROR_MSG_WRONG_CREDENTIALS,
    SHOW_ERROR_MSG_INVALID_PASSWORD,
    SHOW_ERROR_MSG_PASSWORD_MISMATCH
}